# DEV ONLY: anonymous, unencrypted broker. Do not use in production.
listener 1883
allow_anonymous true
persistence false
max_packet_size 32768
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
